### ISSUE TITLE
broken loadWorkbook

### ISSUE THREAD

**Issue by ColinGoodall1** [miraisolutions/xlconnect#102]
wb <- loadWorkBook("test1.xlsx")

gives (first call)

Error: POIXMLException (Java): org.apache.xmlbeans.XmlOptions.setEntityExpansionLimit(I)Lorg/apache/xmlbeans/XmlOptions;

and gives (second and subsequent calls)

 loadWorkbook("test1.xlsx")
Error: POIXMLException (Java): Could not initialize class org.apache.poi.ooxml.POIXMLTypeLoader

In #101, CRAN comments, there is reference to ooxml-schemas-1.4.jar
However, XLConnectJars/java includes ooxml-schemas-1.3.jar only

R.Version:
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          6.3                         
year           2020                        
month          02                          
day            29                          
svn rev        77875                       
language       R                           
version.string R version 3.6.3 (2020-02-29)
nickname       Holding the Windsock

**Comment by spoltier** [comment]
Did you see an error message when installing or when loading XLConnect ?
As of version 1.0, XLConnectJars is no longer required. The required jars should be downloaded on installation.
Among others, _ooxml-schemas.jar_ should be present in the package's installation directory (_your-r-lib/XLConnect/java_).

If you have problems installing, this may be due to a firewall or other proxy blocking downloads from _repo1.maven.org_. You may specify a different maven repository by setting the variable `XLCONNECT_JAVA_REPO_URL` to a maven-compatible public repository or mirror.

**Comment by ColinGoodall1** [comment]
H Simon,

Thanks for following up.
Yes, I have the jar file.
No install errors etc, but I'll try to reinstall.
Thank you for the note that XLConnectJars is no longer required.

I was able to install the older version from the archives, so am running
fine.

**Comment by spoltier** [comment]
This was probably the same problem as #103 and #106 - poi-ooxml-schemas.jar was missing
