### ISSUE TITLE
Simplify "get or create cell style"

### ISSUE THREAD

**Issue by martinstuder** [miraisolutions/xlconnect#14]
Currently there exist two methods for creating and getting cell styles: createCellStyle and getCellStyle. Doing a "get or create cell style" is currently slightly cumbersome as it requires a combination of operations.

**Comment by clarkdk** [comment]
Can you give `getCellStyle()` a `create` argument, like in `loadWorkBook()`? `create = TRUE` would create the cell style if it doesn't already exist, or return an existing cell style. The default would be `create = FALSE` , corresponding to current operation. This would help in programming, since there doesn't seem to be an XLConnect function to test if a cell style already exists.
