### ISSUE TITLE
loadWorkbook fails, possible interaction with other packages?

### ISSUE THREAD

**Issue by assaforon** [miraisolutions/xlconnect#148]
Hi,

Code that previously worked for me now fails right at loadWorkbook() with the error

Error: NoClassDefFoundError (Java): org/apache/poi/openxml4j/exceptions/InvalidFormatException

I'm seeing many message boards with the same error, but no resolution for you.

Thanks,
Assaf

**Comment by spoltier** [comment]
Hi @assaforon it is indeed possible that if you use e.g colearendt/xlsx, you will have a different version of POI on the classpath, which due to the shared classloader creates conflicts.
#142 is a request to solve this particular problem. We are not handling this right away, because it requires raising our dependency to R version 3.6.
Another possible issue is missing java dependencies - they may have failed to download at install time depending on your particular system (this cannot happen on windows unless you build from source).
