### ISSUE TITLE
setForceFormulaRecalculation failing on R 4.2.0+

### ISSUE THREAD

**Issue by ekennedy** [miraisolutions/xlconnect#170]
Calling setForceFormulaRecalculation(wb, sheet = "*", TRUE) produced a warning using R versions less than 4.2.0:

Warning message:
In if (sheet == "*") { :
  the condition has length > 1 and only the first element will be used

When running the same code in R 4.2.0+ the program aborts with an error:

![image](https://user-images.githubusercontent.com/124946/183771431-555d770b-b9f5-464e-86f8-23ca02af6fa1.png)

The R 4.2.0 release notes have the following note under Significant Visible User Changes:

Calling if() or while() with a condition of length greater than one gives an error rather than a warning. Consequently, environment variable _R_CHECK_LENGTH_1_CONDITION_ no longer has any effect.

I ran through the code in the debugger and I don't think the error is actually in R/workbook.setForceFormulaRecalculation.R program.  In my call the if statement on line 35 does not appear to meet the conditions to through the error.  I assume that it must be an error further downstream.

**Comment by Chargothrond** [comment]
Thanks for spotting, this has indeed become a bug since 4.2.0 and needs to be fixed.

The error is in `R/workbook.setForceFormulaRecalculation.R`, but it isn't straight-forward to see how it executes (basically it goes through that if first with the `"*"`, which then triggers it again in a vectorized way in order to apply it to all sheets, but this can fail now, because the `condition has length > 1` warning became an error in R 4.2.0). `R/workbook.getForceFormulaRecalculation.R` suffers from the same problem. #171 will fix both issues and we plan to release a new version soon.
