### ISSUE TITLE
Values read with formatting instead of raw value

### ISSUE THREAD

**Issue by hhoeflin** [miraisolutions/xlconnect#48]
Hi,

I have an excel spreadsheet. In one cell, a value of 0.007% is entered, for 2 digits formatting, so displaying 0.01%. The worksheet has several character rows, so cannot be read as all numeric. 

In this case, the value that is returned from the cell is 0.01% instead of the correct 0.007%

**Comment by martinstuder** [comment]
This is the expected behavior. XLConnect determines the type of a column based on the types for the various cells in that column. If you have mixed numeric and string cells in a column, XLConnect will convert your numeric cells to string (because string is the more generic type). This conversion is done based on the data format for the cell according to "what you see is what you get" (WYSIWYG). Note that you can force the column to be numeric when reading in if that is the desired behavior.

**Comment by hhoeflin** [comment]
Hi,
thank you - I understand. Nonetheless, this behavior led to a substantial error in my calculations and quite a bit of detective work to find out where it came from. 

I was wondering if maybe there is a possibility to include a switch to ignore formats. Of course, the column would still be converted to the generic type - and that is ok - but the raw underlying data would be converted. Of course this would potentially lead to other issues with dates ...

In any case - thank you for your answer.
