### ISSUE TITLE
readNamedRegion() - if region has only 2 columns then can't set first column as rownames

### ISSUE THREAD

**Issue by EldarAgalarov** [miraisolutions/xlconnect#49]
readNamedRegion(workbook, "namedRegion", T, 1) - can't set first column as row names, if only 2 columns in named region. If more columns (> 2) then works fine.

**Comment by EldarAgalarov** [comment]
a-ha, it's not an issue of XLConnect.

**Comment by martinstuder** [comment]
Could you provide a reproducible example and be a bit more specific on what you think is not working? I tried with a simple named region with two columns and reading it in worked fine, although it does simplify the structure, i.e. the result is a vector rather than a data.frame. Is this what you are referring to?

**Comment by EldarAgalarov** [comment]
"Is this what you are referring to?" - yes. It's possible to avoid simplification from data.frame to vector?

**Comment by Deleetdk** [comment]
I seem to have the same problem, namely that simplify = F has no effect. I am loading a sheet with 2 columns and I want to use the first as rownames, and the second as a single column data.frame or even named vector. However, the current output is an unnamed vector.

**Comment by martinstuder** [comment]
Ok, I see. Assuming a workbook `wb` with a sheet containing two columns A and B
```
readWorksheet(wb, sheet = 1, rownames = 1, simplify = FALSE)
```
results in the dimension being dropped although `simplify = FALSE` has been specified.
